version: "2"

run:
  timeout: 5m
  tests: true      # Enable linting for test files.
  exclude-use-default: false

linters-settings:
  staticcheck:
    checks:
      - SA1000 # Customize which specific staticcheck rules to run.
      - SA1019

# issues:
#   exclude-rules:
#     - linters:
#         - errcheck
#       text: "ignoring file write error"  # Exclude specific error messages.
#   max-issues-per-linter: 0  # No maximum issues per linter.
#   max-same-issues: 5        # Prevent spamming with the same issue.
#   exclude-use-default: false

# output:
#   format: colored-line-number # Output format for CLI.

# linters:
#   goanalysis_metalinter:
#     disabled-checkers:
#       - resourceExportData
issues:
  exclude-dirs:
    - vendor
