<<<<<<< HEAD
=======
#This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
#If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
>>>>>>> cb45fd47df91cbe0f9c0913749c2c5e33b6db8ce
builds:
  - binary: terraform-provider-bigip
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
